### ISSUE TITLE
[BUG] Can't select files to import on macOS

### ISSUE THREAD

**Issue by s0q** [sircharlo/jw-meeting-media-fetcher#102]
**Describe the bug**
When using the feature to convert custom media to mp4, the dialogue box doesn't present the jpeg files as valid files to use.

**To Reproduce**
1. Attempt to sync media
2. Click on Custom
3. Attempt to add custom media by specifying the file path in the blank field
4. See screenshot

![image](https://user-images.githubusercontent.com/56456179/133890070-9af182af-84f0-4b69-9a6c-0638f6d179f5.png)

**System specs (please complete the following information):**
 - OS: MacOS 11.5.2
 - App Version 0.9.1

**Comment by sircharlo** [comment]
Hmm. I notice those files are stored in a cloud folder (ie. iCloud or Dropbox). Does this same issue happen when you copy/move the folder with images to a normal, non-synced folder?

**Comment by sircharlo** [comment]
Ok, so apparently this is related to https://github.com/electron/electron/issues/6472. It's an obscure behavior that isn't documented very well, but apparently it's a feature not a bug. 🤷‍♂️ 
Fixed in bugfix release 0.9.2, let me know if it works now.

**Comment by s0q** [comment]
Interesting! Well found.

Although, I've tried to open that new release but I'm getting some trouble, first it said I didn't have permission to run the file:
<img width="274" alt="Screenshot 2021-09-18 at 18 08 25" src="https://user-images.githubusercontent.com/56456179/133896780-01e724fb-c064-4550-a80e-ac4708d46b1b.png">

So I had to `chmod -x` it, it opens now, but I'm a little stuck at this error:
<img width="372" alt="Screenshot 2021-09-18 at 18 10 20" src="https://user-images.githubusercontent.com/56456179/133896851-fb9b2a06-91b0-4944-aad3-9e504b239ccb.png">

Here's the crash dump:

`Process:               JW Meeting Media Fetcher [8794]
Path:                  /Applications/JW Meeting Media Fetcher.app/Contents/MacOS/JW Meeting Media Fetcher
Identifier:            sircharlo.jw-meeting-media-fetcher
Version:               0.9.2 (0.9.2)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           JW Meeting Media Fetcher [8794]
User ID:               502

Date/Time:             2021-09-18 18:04:41.863 +0100
OS Version:            macOS 11.5.2 (20G95)
Report Version:        12
Bridge OS Version:     5.5 (18P4759a)
Anonymous UUID:        0ACCDF45-5FFA-AA5C-4F16-CF6B36932085

Sleep/Wake UUID:       B22A81E2-1FC0-48BA-8BDE-F8CC65FA3E37

Time Awake Since Boot: 120000 seconds
Time Since Wake:       350 seconds

System Integrity Protection: disabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 0C9EB0DE-F5CE-3AFC-8F08-0C6DB1E7FC44
Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/JW Meeting Media Fetcher.app/Contents/MacOS/JW Meeting Media Fetcher
  Reason: no suitable image found.  Did find:
	/Applications/JW Meeting Media Fetcher.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Applications/JW Meeting Media Fetcher.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x10310d000 -        0x10315cfff +sircharlo.jw-meeting-media-fetcher (0.9.2 - 0.9.2) <397A5A70-F1A4-3193-A150-5CD75A8C22CF> /Applications/JW Meeting Media Fetcher.app/Contents/MacOS/JW Meeting Media Fetcher
       0x105383000 -        0x10541efff  dyld (852.2) <57DB2053-BFD5-3683-97C6-F1DB2A1F1D09> /usr/lib/dyld

Model: MacBookPro15,2, BootROM 1554.140.20.0.0 (iBridge: 18.16.14759.0.1,0), 4 processors, Quad-Core Intel Core i5, 2.3 GHz, 8 GB, SMC 
Graphics: kHW_IntelIrisGraphics655Item, Intel Iris Plus Graphics 655, spdisplays_builtin
Memory Module: BANK 0/ChannelA-DIMM0, 4 GB, LPDDR3, 2133 MHz, Micron, -
Memory Module: BANK 2/ChannelB-DIMM0, 4 GB, LPDDR3, 2133 MHz, Micron, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Jul  7 2021 02:34:10 version 9.30.444.17.32.5.70 FWID 01-4075fabc
Bluetooth: Version 8.0.5d7, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: Apple T2 Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.5
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.5
`
Sorry to trouble you!

**Comment by sircharlo** [comment]
No trouble! I tried it on my Mac VM with no issues. Did you try to open the zip file from GitHub with the built-in 'Archive Utility'? This problem is usually an issue with the unzipper used. Try deleting the JWMMF app, and unzipping the zip the built-in Archive Utility and see if that changes anything.

**Comment by s0q** [comment]
Ah, it works now, I was trying the appimage and also the zip file, the dmg is what I'd always used previously so that's it settled then. 
And just confirming, the file picker is fixed, thank you much!

**Comment by sircharlo** [comment]
The joys of lazy cross platform development!
