### ISSUE TITLE
Congregation media syncing

### ISSUE THREAD

**Issue by mattapperson** [sircharlo/jw-meeting-media-fetcher#14]
Any chance we can get the congregation media syncing feature to be able to upload images in the app and have JMMF convert it for zoom to an mp4 without sftp?

**Comment by sircharlo** [comment]
Hmm. I hadn't thought about that scenario. I'd have to think about the best way to implement this.

**Comment by sircharlo** [comment]
Added option "Enable conversion of additional media" in v0.8.86.
