### ISSUE TITLE
[BUG] Missing media from Teaching BOX

### ISSUE THREAD

**Issue by jakubnavratil** [sircharlo/jw-meeting-media-fetcher#140]
**Describe the bug**
Today 02.12.2021 we had article (https://wol.jw.org/en/wol/d/r1/lp-e/1102017176#h=21:0-28:0) which contains BOX at Question 19.
In that BOX (https://wol.jw.org/en/wol/d/r1/lp-e/1102017946) there are three images.
All images are missing in downloaded folder but one, which is preview of that BOX inside article.

**Expected behavior**
All media associated with meeting downloaded

**Comment by sircharlo** [comment]
Very true! Thanks for pointing that out. 
We don't use the _rr_ book in my congregation's language, so I hadn't noticed that issue. in 
I just released a new version of the app to fix this (#141), along with an explanatory note upon first launch; JWMMF should auto-update the next time you open it, unless you're on a Mac, in which case you'll need to get the latest update manually. 
Please let me know if the issue still persists after updating.
