### ISSUE TITLE
Error downloading this week's publications [BUG]

### ISSUE THREAD

**Issue by e-Feitosa** [sircharlo/jw-meeting-media-fetcher#143]
When downloading the publications of this week (weekend), the publications of the next week are showing up, i.e., the downloaded images and songs are from the week of December 06. You can check about! Thank you in advance for your excellent work. And I would like to ask if it would be possible to leave the two options, download media and convert to mp4 and keep the images of the publications.

![image](https://user-images.githubusercontent.com/90984283/144686644-73150d1d-ad1a-42c9-952b-8935838b33d9.png)

**Comment by sircharlo** [comment]
Wow. Thanks for this. I don't have time to go in-depth and see why the usual 8-week calculation didn't work this time around; I did just push an update that'll take care of this bug. 
Install the latest release #144, and you might want to clean your media cache too. The media should be fine now.

**Comment by sircharlo** [comment]
> And I would like to ask if it would be possible to leave the two options, download media and convert to mp4 and keep the images of the publications.

Good idea; I'll try to think of something like that for a future release.
