### ISSUE TITLE
[BUG] Can't download media for 2022-01-03 - 2022-01-09

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/jw-meeting-media-fetcher#147]
**Describe the bug**
Today, December 8th 2021, I can download every listed weeks media, except the last available week (Jan 3rd - Jan 9th). It freezes after the days have turned green.

**To Reproduce**
1. Go to 'Home'
2. Select week '2022-01-03 - 2022-01-09'
3. Click 'Get media!'

**Expected behavior**
I expect that the fetcher would just download the media for that week.

**Logs**
The [API call](https://b.jw-cdn.org/apis/pub-media/GETPUBMEDIALINKS?output=json&pub=mwbv&track=1&issue=20220100&langwritten=O ) returns a 404 not found error. It can't find contents in the Life and Ministry—Meeting Workbook of January 2022.

**Screenshots**
![Screenshot 2021-12-08 214817](https://user-images.githubusercontent.com/46671786/145282164-be1871bb-13cb-40a1-8b7a-ad2b78d61eb5.png)

**System specs (please complete the following information):**
 - OS: Windows 10
 - App Version 21.12.1

**Additional context**

**Comment by sircharlo** [comment]
Hi there!
This is in fact a bug that I had noticed; it has been fixed as of https://github.com/sircharlo/jw-meeting-media-fetcher/commit/38f20e77a1f7433c38d4a5e54b26847ead79e921.
However, I don't feel that this fix requires an emergency bugfix release, as the issue only presents itself in cases where linked media is not yet available, which so far has never happened for meetings that will take place within 2-3 weeks. An update to the app including this fix will be released at the very latest with the next monthly release, around early January.
