### ISSUE TITLE
[ENHANCEMENT] Custom songs added with proper name

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/jw-meeting-media-fetcher#149]
Hi @sircharlo, when selecting custom songs to be added to the media, they get the generated filename from jw.org, which doesn't tell you what you want to know. Instead I would like to see the filename be the same as songs that get added automatically, because they are part of that weeks meeting. This shouldn't be too hard, because those names are already shown when searching for a song.

**Comment by mtdvlpr** [comment]
@sircharlo

**Comment by sircharlo** [comment]
Believe it or not, I had noticed this inconsistency but never bothered to change it. In any case.. https://github.com/sircharlo/jw-meeting-media-fetcher/commit/00f92b2e84508fec8e2092e2e2363a0a4556e40b has been pushed 😃 
Slated for next release.
