### ISSUE TITLE
[BUG] App closes after syncing 

### ISSUE THREAD

**Issue by s0q** [sircharlo/jw-meeting-media-fetcher#16]
**Describe the bug**
I'm not sure whether this a bug or not, but when i first ran this, it came up with all the options like it does in the readme. But now I can never seem to get back to those options. It simply downloads the files and closes. I ticket the box to ask it to update and then open the folder where the files are stored, maybe there was an option i ticked to close the program after syncing too.

**To Reproduce**
Try to open app, after freshly installing.

Or, try to open app after having used it before.

Get stuck at this page.
![image](https://user-images.githubusercontent.com/56456179/108764586-b636b380-754a-11eb-9a43-7883aeb45d6f.png)

Then the app quits.

**Expected behavior**
Get to the menu with all the options and settings

**Logs**
Can't seem to get logs with that shortut on MacOS.

**System specs (please complete the following information):**
 - OS: MacOS Big Sur 11.2.1
 - App Version 0.8.85

Great App btw our sound team is looking forward to using it.

**Comment by sircharlo** [comment]
Try to delete the app completely, and to redownload the latest version from [here](https://github.com/sircharlo/jw-meeting-media-fetcher/releases).
I think for future releases I'll disable the auto-update mechanism for Mac. 
Sorry for the trouble mate!

**Comment by s0q** [comment]
Thanks for the lightspeed reply, really helpful.

Okay so updating got us further.
It works fine now for as a fresh install for my team.

Now with mine, I can see the day selector and the mp4 conversion button, but i believe i ticked the option to quit the app after syncing. And I can't figure out where to unselect that option.

![image](https://user-images.githubusercontent.com/56456179/108767388-4b877700-754e-11eb-88eb-d6170ef11f34.png)

The last setting there.

**Comment by sircharlo** [comment]
If I understand correctly, you mean that the app opens, does its thing, and exits upon completion, and you want to prevent that from happening (if at least temporarily)
Try clicking on the checkmark after the media sync on the smiley screen:
![iwkIzXCOvJ](https://user-images.githubusercontent.com/1275666/108768045-321e0500-7525-11eb-810b-a2f72b1613f5.png)
It'll turn green, and the program will not exit automatically.

I think I'll add some labels to indicate that those buttons are actionable 😄

From there, you'll be able to access the settings from the bottom right on the main screen.

**Comment by s0q** [comment]
Nice, that worked for me, thank you!!

**Comment by sircharlo** [comment]
Pleasure! Glad it works for you.
I'll reopen the issue until I release the next update (sometime this week hopefully) , to address the Mac-auto-update crashing issue.
Keep an eye out, the next update I'll release will disable forced updating for Mac (which is broken because of the nature of Mac security).
I'll have a button show up for Mac users when an update is available that will take you to the download screen.
So next time the app "breaks" for you in the near future.. Download the newest version 😆

**Comment by s0q** [comment]
> because of the nature of Mac security
Everytime...

You're an absolute legend, and this app is great.

**Comment by sircharlo** [comment]
Well, I had a bit of time 😅 
New release out which should prevent Mac users such as yourself from getting the behaviour you saw.
