### ISSUE TITLE
Download problems of week January 10, 2022

### ISSUE THREAD

**Issue by giuenara** [sircharlo/jw-meeting-media-fetcher#162]
There is a problem with the download of next week's images (January 10, 2022).
![2022-01-07 10_27_40-JW Meeting Media Fetcher](https://user-images.githubusercontent.com/82910804/148523420-4f720945-bee8-4299-a130-ea34f753a789.png)

**Comment by sircharlo** [comment]
Thank you for reporting this! This issue wasn't present in English or Russian, but in Spanish it was. It has to do with older publications and how they were formatted. 

In any case, https://github.com/sircharlo/jw-meeting-media-fetcher/commit/a7794ce860755dd833abdbc0890ee75de5ed26af fixes it. I will release a new version of JWMMF later today with a few new features, and this fix will be included.

Thanks again!
