### ISSUE TITLE
Conversion Failure

### ISSUE THREAD

**Issue by danielferraz-git** [sircharlo/jw-meeting-media-fetcher#171]
Description:
When downloading the media for the meeting in Portuguese, I get the error that the .jpg images cannot be converted.

**Screenshots**
![image](https://user-images.githubusercontent.com/46219732/149849220-e860f283-e93f-4618-baba-05837015c117.png)

**System specs (please complete the following information):**
 - OS: Windows 10.1.043
 - App Version: 22.1.1

**Comment by sircharlo** [comment]
Hi there @danielferraz-git !
I tried but was unable to replicate this issue:
![2022 01 17-21 33 37 CUserssirchVideosMeeting_MediaT2022-01-20](https://user-images.githubusercontent.com/1275666/149860929-b8caa2f4-0278-41ab-aa41-58ef28862748.png)

Could you try again and post the output from the console when the error happens? (<kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>I</kbd>) 

Something like this: 
![image](https://user-images.githubusercontent.com/1275666/149861171-8bc4f4d4-fdef-4028-8904-69e7a55d01c9.png)

Thanks

**Comment by danielferraz-git** [comment]
This is the problem, it doesn't find the file in the folder, I would say that the problem may be related to the accent, since one of the folders has a Brazilian Portuguese accent:

![image](https://user-images.githubusercontent.com/46219732/150012514-491055f1-c615-451b-bda0-c0101500227e.png)

**Comment by sircharlo** [comment]
Oh, interesting. I'll test folders with accents to see what causes this.

**Comment by sircharlo** [comment]
What was the folder name exactly?

**Comment by sircharlo** [comment]
Ho! I think I got it. I was able to reproduce the error, but I think the Portuguese accents were just a red herring. I think we're hitting Windows' [260 character limit for filepaths](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation).

I'll release a patch soon to cap filename length at less than 260 characters including full path.

**Comment by sircharlo** [comment]
Fixed in https://github.com/sircharlo/jw-meeting-media-fetcher/commit/1edd6d62e94b1ee09e40fc970556b89d54d04f07

**Comment by sircharlo** [comment]
Released in #173
