### ISSUE TITLE
Unexpected images

### ISSUE THREAD

**Issue by tinhojw** [sircharlo/jw-meeting-media-fetcher#174]
### To Reproduce
3. Do '....'

### Screenshots
If possible, add screenshots to help explain your problem.

### System specs
- Windows_NT 10.0.19043
- JWMMF v22.1.2

### Anonymized `prefs.json`
```
{
  "autoOpenFolderWhenDone": true,
  "autoQuitWhenDone": null,
  "autoRunAtBoot": null,
  "autoStartSync": null,
  "congServer": null,
  "congServerPass": null,
  "congServerPort": null,
  "congServerUser": null,
  "enableMp4Conversion": true,
  "enableMusicButton": null,
  "enableMusicFadeOut": null,
  "excludeLffi": true,
  "excludeLffiImages": null,
  "excludeTh": true,
  "lang": "T",
  "langUpdatedLast": "2022-01-22T14:12:25.433Z",
  "localAdditionalMediaPrompt": true,
  "localAppLang": "pt",
  "localOutputPath": "***",
  "maxRes": "720p",
  "musicFadeOutTime": "5",
  "musicFadeOutType": null,
  "mwDay": "2",
  "mwStartTime": null,
  "weDay": "5",
  "weStartTime": null
}
```

**Comment by sircharlo** [comment]
@tinhojw Hi there! What's the issue exactly?

**Comment by tinhojw** [comment]
Meu aplicativo está baixando as imagens de discurso ou da broxura lffi

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sircharlo** [comment]
Your preferences are set like this: 
![image](https://user-images.githubusercontent.com/1275666/150643409-d34bde9b-d0b7-4fae-8ad9-5292484d5c22.png)

This results in this:
![image](https://user-images.githubusercontent.com/1275666/150643425-33285e42-1bab-4eaa-bf21-477b47df38d7.png)

However, this:
![image](https://user-images.githubusercontent.com/1275666/150643442-599992c5-7d1c-4c5b-a3dc-2db2b43eb738.png)

Results in this:
![image](https://user-images.githubusercontent.com/1275666/150643475-9cdd8cff-73ea-434b-8cfd-eadebf00cfc1.png)

All seems to work as expected, unless there's something that I misunderstood?

**Comment by tinhojw** [comment]
A minha está configurado como o exemplo último porém está baixando as imagem do discurso 5 minutos

Obter o Outlook para Android<https://aka.ms/AAb9ysg>

________________________________
De: Charles Olivier Savignac ***@***.***>
Enviado: sábado, 22 de janeiro de 2022 11:52
Para: sircharlo/jw-meeting-media-fetcher
Cc: tinhojw; Mention
Assunto: Re: [sircharlo/jw-meeting-media-fetcher] imagens (Issue #174)


Your preferences are set like this:
[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1275666%2F150643409-d34bde9b-d0b7-4fae-8ad9-5292484d5c22.png&data=04%7C01%7C%7Ca78b6735465b455cd7a008d9ddb6df7c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637784599776208734%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=S3rTUIrCz8Tm32c7eQ7BeYCIXIwXqxyYRIItRxbPOiA%3D&reserved=0>

This results in this:
[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1275666%2F150643425-33285e42-1bab-4eaa-bf21-477b47df38d7.png&data=04%7C01%7C%7Ca78b6735465b455cd7a008d9ddb6df7c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637784599776208734%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=50STxjFmWBy0%2Fw%2BxH3MAMHf2XXPttbh837m7MoVsVEA%3D&reserved=0>

However, this:
[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1275666%2F150643442-599992c5-7d1c-4c5b-a3dc-2db2b43eb738.png&data=04%7C01%7C%7Ca78b6735465b455cd7a008d9ddb6df7c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637784599776208734%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WYrUP7zawumUzgrKbrTZWnGHDTOhMdVji2%2F1h%2FNPk3k%3D&reserved=0>

Results in this:
[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1275666%2F150643475-9cdd8cff-73ea-434b-8cfd-eadebf00cfc1.png&data=04%7C01%7C%7Ca78b6735465b455cd7a008d9ddb6df7c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637784599776208734%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=eDOZZm%2B0Tzums65V86iyCJlQUgXA5rcLy%2F6VJnNfg9w%3D&reserved=0>

All seems to work as expected, unless there's something that I misunderstood?

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsircharlo%2Fjw-meeting-media-fetcher%2Fissues%2F174%23issuecomment-1019285439&data=04%7C01%7C%7Ca78b6735465b455cd7a008d9ddb6df7c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637784599776208734%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2ckBSFS7y7PdfEmNpFBPp%2BTMou7%2Frz%2FguhM6ehgE%2BV4%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXNL7FI2SEBURGJ2RGYDEN3UXLAEPANCNFSM5MSBG4OA&data=04%7C01%7C%7Ca78b6735465b455cd7a008d9ddb6df7c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637784599776208734%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=aPKTnhjPzgwcfOGwjgdoGN4VZ4bZxzZsrxdcI6qOJWg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Ca78b6735465b455cd7a008d9ddb6df7c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637784599776208734%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NTbfWbOTn1QPV%2B1T9FC0TuP0CMPcME%2FnMgOAG6hWU14%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Ca78b6735465b455cd7a008d9ddb6df7c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637784599776208734%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=KkO4r4OSuZeL7MuYlRdpiFC%2BS2Zuq5Pd%2FB%2F13hJyC0c%3D&reserved=0>.

**Comment by sircharlo** [comment]
Could you post screenshots of your media settings and the resulting media files please?

**Comment by tinhojw** [comment]
Acho que entendi na parte 5 minutos discurso ele baixou uma imagem que vem logo após a imagem de tesouros, por ser discurso o programa o baixou

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sircharlo** [comment]
Yes, JWMMF downloads all relevant images. In this case, the image from the 5-minute talk will be used in many congregations, therefore it is there.
If media is possibly relevant, it will be downloaded. Better to download more and remove what won't be needed that to be missing a picture!
Let me know if you need additional clarifications or help.

**Comment by tinhojw** [comment]
Ótimo parabéns somente semana passada programa n baixou vídeo introdução livro mas baixei rapidamente.
Obg

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sircharlo** [comment]
If ever media is missing in the future, let me know. That shouldn't happen. I'll take a look and see why that is.
Enjoy!

**Comment by tinhojw** [comment]
Ok estarei atento

Obter o Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
