### ISSUE TITLE
[BUG] Duplicate media being downloaded

### ISSUE THREAD

**Issue by JasonRaveling** [sircharlo/jw-meeting-media-fetcher#191]
**Describe the bug**
Maybe this has to do with the RSS feed (or whatever you use  to pull the  data) rather than your app itself. I thought I'd pass this along. When running the fetcher, I get all of the media but some are duplicates. See the example below. This is output of `sha1sum` showing that the duplicates are the same exact file. This has happened for the past few weeks. The files below are from the week of 2022-02-08.

    ...
    01a948632020710e0577e3c1be4a2024  ./02-01 - Introduction to 1 Samuel.mp4
    01a948632020710e0577e3c1be4a2024  ./02-03 - Introduction to 1 Samuel.mp4
    ...
    714fa15d7b8a5513821dbfdc6a155404  ./08-01 - My Teen Life—How Can I Talk to My Parents.mp4
    714fa15d7b8a5513821dbfdc6a155404  ./08-02 - My Teen Life—How Can I Talk to My Parents.mp4
    ...

**To Reproduce**
1. Run `./JW-Meeting-Media-Fetcher.AppImage`

**Logs**

    Checking for update
    Update for version 22.1.2 is not available (latest version: 22.1.2, downgrade is disallowed).

**System specs (please complete the following information):**
 - OS: Debian 11
 - App Version 22.1.2 (AppImage)

**Compliments :-)**
Thanks for this tool and JW Launcher. I just setup a computer for someone who is making good use of JW Launcher. I wish I found it 2 years ago. It would have made things easier for so many!

**Comment by sircharlo** [comment]
Thank you so much for the kind words! I'm happy to hear that my humble little apps can help some dear ones 😄 

As for the bug, that's definitely interesting. Thank you for bringing that to my attention. 

In Russian (language of my congregation), I noticed no such bug. But it is indeed present in English, and other languages as well in fact. Long story short, some languages' publication databases are structured in a slightly different way than others, resulting in some media being duplicated for those languages.
I'll come up with a workaround to avoid duplicates like this in time for the next release, due sometime before next week.

Thank you!

**Comment by sircharlo** [comment]
Fixed in https://github.com/sircharlo/jw-meeting-media-fetcher/commit/ae7c667ca9a5729d7e0e1cd7febe7a243ea2fe66. Will be released in a few days.
