### ISSUE TITLE
Converting the images to MP4?

### ISSUE THREAD

**Issue by ajtruckle** [sircharlo/jw-meeting-media-fetcher#200]
Dear Brothers

Thanks for your software which I am just reviewing.

May I kindly ask if there is a setting to convert the JPG files to MP4? I know I can manually do this on my Windows 11 PC with builtin software.

Thanks for confirming.

Your brother

Andrew

**Comment by ajtruckle** [comment]
Ignore!

**Comment by sircharlo** [comment]
Glad you found what you were looking for 😄
