### ISSUE TITLE
How come the Intro Video did not download for the CBS Study (chap 22)?

### ISSUE THREAD

**Issue by ajtruckle** [sircharlo/jw-meeting-media-fetcher#221]
### Describe the bug
I downloaded the media for this week. Everything is there but not the intro video for the CBS study?

### To Reproduce
1. Download media for this week (14 March 2022 - English)

### Expected behavior
Download the intro video as it is part of the meeting media.

### Screenshots
N/ A

### System specs
- Windows 11 10.0.22000
- JWMMF v22.3.0

### Additional context
N / A

### Anonymized `prefs.json`
```
{
  "autoOpenFolderWhenDone": true,
  "autoQuitWhenDone": null,
  "autoRunAtBoot": null,
  "autoStartSync": null,
  "congServer": null,
  "congServerPass": null,
  "congServerPort": null,
  "congServerUser": null,
  "enableMp4Conversion": true,
  "enableMusicButton": null,
  "enableMusicFadeOut": null,
  "excludeLffi": true,
  "excludeLffiImages": true,
  "excludeTh": true,
  "keepOriginalsAfterConversion": true,
  "lang": "E",
  "langUpdatedLast": "2022-03-14T15:08:02.529Z",
  "localAdditionalMediaPrompt": true,
  "localAppLang": "en",
  "localOutputPath": "***",
  "maxRes": "720p",
  "musicFadeOutTime": null,
  "musicFadeOutType": null,
  "musicVolume": null,
  "mwDay": "3",
  "mwStartTime": null,
  "weDay": "6",
  "weStartTime": null
}
```

**Comment by sircharlo** [comment]
Hi there!
I copied your settings and ran the sync, this is what I saw:

![image](https://user-images.githubusercontent.com/1275666/158275323-3a105e41-31ec-49f0-91dc-8bf6141c6275.png)

I see the introduction video you mention, under 07.02. Do you not see it on your system?

**Comment by Chipperchap** [comment]
Hi Brothers
If it helps, I can confirm it is working okay in this part of the world. 
Kind regards
Simon

**Comment by ajtruckle** [comment]
Hi!

> I see the introduction video you mention, under 07.02. Do you not see it on your system?

Sorry for the confusion on my part. For some reason I was bring drawn to the thumbnails of the images (that were turned into videos) instead of the other ones. I see it now. Oops.

**Comment by sircharlo** [comment]
Glad to hear it!
