### ISSUE TITLE
Yeartext Display Question

### ISSUE THREAD

**Issue by khcarmel** [sircharlo/jw-meeting-media-fetcher#226]
Good afternoon, my issue seems to be with the years text in any language other than English. As I am new to this software it may be user error. However when I change the language the year texts does not appear only the JW in the lower right hand.

**Comment by khcarmel** [comment]
Good afternoon, my issue seems to be with the years text in any language other than English. As I am new to this software it may be user error. However when I change the language the year texts does not appear only the JW in the lower right hand.

**Comment by sircharlo** [comment]
Have you opened JW Library and see the yeartext in the language you want displayed in the JW Library black media screen?
For JWMMF to retrieve the yeartext in the desired language, it needs to be displayed at least once in JW Library itself.

**Comment by sircharlo** [comment]
Did you have success finally @khcarmel ?

**Comment by sircharlo** [comment]
I'll close this for now, as there doesn't seem to be an easy way to fetch the yeartext, other than by opening JW Library and going to the meetings tab in the desired language. If something changes in the future, I'll implement a more automated solution.
