### ISSUE TITLE
Texto do ano

### ISSUE THREAD

**Issue by djnpinho** [sircharlo/jw-meeting-media-fetcher#249]
![Apresentação1](https://user-images.githubusercontent.com/103318556/162589824-363a9291-02c9-4a19-8906-0cd5222fb440.jpg)
 linha de comando abaixo do texto do ano

**Comment by sircharlo** [comment]
Hm. Haven't seen that one yet. Is this on a Mac?

**Comment by djnpinho** [comment]
Not. Windows 11

Em sáb, 9 de abr de 2022 18:08, Charles Olivier Savignac <
***@***.***> escreveu:

**Comment by sircharlo** [comment]
If I post a beta update here, could you try to install it and tell me if the problem goes away?

**Comment by sircharlo** [comment]
Here is the beta:
https://www.icloud.com/iclouddrive/071hVaPaIGRxLQM0VmfGqnpgg#JW-Meeting-Media-Fetcher-Setup-22.4

**Comment by djnpinho** [comment]
Boa noite
Instalei o beta e ficou perfeito.
Problema resolvido!!
Fica com Jeová

**Comment by sircharlo** [comment]
Perfect! Thanks for letting me know. I'll release it since it fixes the issue 🙂
