### ISSUE TITLE
Thumbnail does not appear in some media

### ISSUE THREAD

**Issue by joaochris** [sircharlo/jw-meeting-media-fetcher#268]
### Describe the bug
In the secondary screen display mode, the thumbnail of some media does not appear.

### To Reproduce
Starting the program and then clicking on the secondary view.

### Screenshots

https://user-images.githubusercontent.com/76891864/165409486-5aa55aa3-6952-49fd-bb03-1d74b6d4df17.mp4

![Screenshot_2](https://user-images.githubusercontent.com/76891864/165408310-5d0434fa-b889-45ed-818c-14eecd0d3af4.png)

### System specs
- Windows_NT 10.0.19044
- JWMMF v22.4.2
- 
### Anonymized `prefs.json`
```
{
  "autoOpenFolderWhenDone": null,
  "autoQuitWhenDone": null,
  "autoRunAtBoot": null,
  "autoStartSync": null,
  "congServer": "***",
  "congServerDir": "***",
  "congServerPass": "***",
  "congServerPort": "***",
  "congServerUser": "***",
  "congregationName": "***",
  "enableMediaDisplayButton": true,
  "enableMp4Conversion": null,
  "enableMusicButton": true,
  "enableMusicFadeOut": null,
  "enableVlcPlaylistCreation": null,
  "excludeLffi": true,
  "excludeLffiImages": true,
  "excludeTh": true,
  "keepOriginalsAfterConversion": null,
  "lang": "T",
  "langUpdatedLast": "2022-04-26T22:51:54.960Z",
  "localAdditionalMediaPrompt": null,
  "localAppLang": "pt",
  "localOutputPath": "***",
  "maxRes": "720p",
  "musicFadeOutTime": null,
  "musicFadeOutType": null,
  "musicVolume": "100",
  "mwDay": "3",
  "mwStartTime": null,
  "weDay": "6",
  "weStartTime": null
}
```

**Comment by sircharlo** [comment]
Odd; does the media play properly though?

Here's what I see:
![image](https://user-images.githubusercontent.com/1275666/165518995-34c3fe43-c8a3-45b0-99f8-e8dbad6cd36e.png)

And it also works in the current development version:
![image](https://user-images.githubusercontent.com/1275666/165519442-41d9a8e1-0c11-43ab-9fa6-c2dd7bcb7695.png)

**Comment by sircharlo** [comment]
Awesome! Good to hear 😉
