### ISSUE TITLE
The song list does not appear.

### ISSUE THREAD

**Issue by joaochris** [sircharlo/jw-meeting-media-fetcher#284]
**To Reproduce**
Installing JWMMF for the first time. By clicking on the day of the meeting, and then selecting the song option.

**Screenshots**
![1](https://user-images.githubusercontent.com/76891864/167135845-a92c1b8b-47a0-445b-b8d4-4bb82fcd1bfc.png)

**System specs:**
 - OS: Windows 10
 - App Version: 22.5.1

**Comment by sircharlo** [comment]
Got it. Will be released in update today.
Temporary workaround for now: restart app 😉

**Comment by sircharlo** [comment]
https://github.com/sircharlo/jw-meeting-media-fetcher/commit/02b0d2050c6433a25af7d100eda2429bb4703e81
