### ISSUE TITLE
[BUG] Close yeartext button doesn't work anymore

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/jw-meeting-media-fetcher#288]
### Describe the bug
When I click on the 'close yeartext screen' button, it continues to blink blue, but the yeartext does not dissappear and clicking the button again does not do anything. The application console does not display anything.

### To Reproduce
1. Go to 'home'
2. Click on 'close 2nd screen'

### Expected behavior
I expect the 2nd screen to close and open again on another click, like it did before.

### Screenshots
![Screenshot from 2022-05-07 09-58-51](https://user-images.githubusercontent.com/46671786/167244979-4d518f7d-5c5b-4962-ab5a-e9c5d3c5cbff.png)

### System specs
- Linux 5.13.0-40-generic
- JWMMF v22.5.2

### Anonymized `prefs.json`
```
{
  "autoOpenFolderWhenDone": null,
  "autoQuitWhenDone": null,
  "autoRunAtBoot": null,
  "autoStartSync": true,
  "congServer": null,
  "congServerPass": null,
  "congServerPort": null,
  "congServerUser": null,
  "congregationName": "***",
  "disableHardwareAcceleration": null,
  "enableMediaDisplayButton": true,
  "enableMp4Conversion": null,
  "enableMusicButton": true,
  "enableMusicFadeOut": true,
  "enableObs": null,
  "enableVlcPlaylistCreation": null,
  "excludeLffi": true,
  "excludeLffiImages": true,
  "excludeTh": true,
  "keepOriginalsAfterConversion": null,
  "lang": "O",
  "langUpdatedLast": "2022-05-07T07:51:29.652Z",
  "localAdditionalMediaPrompt": true,
  "localAppLang": "en",
  "localOutputPath": "***",
  "maxRes": "720p",
  "musicFadeOutTime": "60",
  "musicFadeOutType": "smart",
  "musicVolume": "100",
  "mwDay": "2",
  "mwStartTime": "19:15",
  "obsCameraScene": "Camera",
  "obsMediaScene": "Media",
  "obsPassword": "1914",
  "obsPort": "4444",
  "preferredOutput": 14823010455717188,
  "weDay": "5",
  "weStartTime": "18:00"
}
```

**Comment by sircharlo** [comment]
You’re on Linux. 🤔 

I started using a graceful fade when that button is clicked, instead of an immediate show/hide.

The docs for [that part](https://www.electronjs.org/docs/latest/api/browser-window#winsetopacityopacity-windows-macos) of the Electron framework:

> `win.setOpacity(opacity)`
> `opacity` number - between 0.0 (fully transparent) and 1.0 (fully opaque)
> Sets the opacity of the window. **On Linux, does nothing.** Out of bound number values are clamped to the [0, 1] range.

I hadn’t paid to that tidbit. I'll add a condition for Linux torevert to the old behavior in that case.

**Comment by mtdvlpr** [comment]
Thank you! We're using Windows in the kingdom hall, so it's not a big issue. I was testing the new functionalities on my personal laptop to prepare for tonights meeting.

**Comment by sircharlo** [comment]
No worries; my goal is to have feature parity for all configurations, so this is still an important issue! New build being released within 15 minutes.

**Comment by sircharlo** [comment]
Released.
