### ISSUE TITLE
[BUG] JWMMF crashes when handling PDF

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/jw-meeting-media-fetcher#289]
### Describe the bug
When I try to add a PDF as custom media and press 'update media folders', the media fetcher crashes and disables a lot of functionalities.

### To Reproduce
1. Go to 'home'
2. Click on any day of the week
3. Add a PDF to the media for that day
4. Click 'update media folders'
5. See error

### Expected behavior
I expect the PDF to be converted to images and properly displayed in the media presentation list

### Screenshots

![Screenshot from 2022-05-07 16-36-38](https://user-images.githubusercontent.com/46671786/167259251-6d64aaad-db80-4e29-8a57-c0136943a5c8.png)

### System specs
- Linux 5.13.0-40-generic
- JWMMF v22.5.3

### Anonymized `prefs.json`
```
{
  "disableHardwareAcceleration": null,
  "localAppLang": "en",
  "lang": "O",
  "mwDay": "2",
  "weDay": "5",
  "autoStartSync": null,
  "autoRunAtBoot": null,
  "autoQuitWhenDone": null,
  "localOutputPath": "***",
  "enableMp4Conversion": null,
  "keepOriginalsAfterConversion": null,
  "congServer": null,
  "congServerPort": null,
  "congServerUser": null,
  "congServerPass": null,
  "autoOpenFolderWhenDone": null,
  "maxRes": "720p",
  "enableMusicButton": true,
  "enableMusicFadeOut": true,
  "musicFadeOutTime": "60",
  "musicFadeOutType": "smart",
  "musicVolume": "100",
  "mwStartTime": "19:15",
  "weStartTime": "18:00",
  "excludeTh": null,
  "excludeLffi": null,
  "excludeLffiImages": null,
  "enableVlcPlaylistCreation": null,
  "enableMediaDisplayButton": null,
  "congregationName": "***",
  "enableObs": null,
  "obsPort": null,
  "obsPassword": null,
  "obsMediaScene": null,
  "obsCameraScene": null,
  "preferredOutput": null,
  "langUpdatedLast": "2022-05-07T14:42:49.704Z"
}
```

**Comment by sircharlo** [comment]
Fixed in [this commit](https://github.com/sircharlo/jw-meeting-media-fetcher/commit/617df4eeda4b77012699e45af9a4d4d3cde0237e).
v22.5.4 is now out 😉
