### ISSUE TITLE
Bug: after clearing cache files need to restart JWMMF

### ISSUE THREAD

**Issue by sircharlo** [sircharlo/jw-meeting-media-fetcher#320]
<div type='discussions-op-text'>

<sup>Originally posted by **riemsesy** May 11, 2022</sup>
let's say you've created the media list and then fetched all media.
Then you go back to the config screen and clear the cache
Then you want to create the media list again 
then when fetching media
a lot of errors appear and downloading is very slowly, it doesn't finish

a movie says more than a million words
wrong movie

</div>

**Comment by sircharlo** [comment]
@riemsesy I've transferred this here, as it's a bug, not a discussion.

However, I can't reproduce it. Works fine for me. Can you post the contents of the inspector when you see these errors please?

**Comment by riemsesy** [comment]
https://1drv.ms/u/s!Ar84CcBfxBgNr6Er7t3cWKFOlTYPdw?e=gmSomz

**Comment by sircharlo** [comment]
Fixed. One little line 😄 
https://github.com/sircharlo/jw-meeting-media-fetcher/commit/c6a0c6df93339712dc78ff202a2b182a46e45315

**Comment by riemsesy** [comment]
Thank you! 👍🏻
