### ISSUE TITLE
Two icons

### ISSUE THREAD

**Issue by e-Feitosa** [sircharlo/jw-meeting-media-fetcher#321]
Hello, **would it be possible to differentiate the two icons, see in the picture that the two are the same**, it could be different colors or the icon of the second screen having the name 2 or something related to the screen 2 display.

![image](https://user-images.githubusercontent.com/90984283/167940711-239b8094-65b8-461f-b00c-3cbb8f2c6b60.png)

**Comment by joaochris** [comment]
It's already been done [here!](https://github.com/sircharlo/jw-meeting-media-fetcher/commit/92640ced3f71105a74eba692126e2d487c0b594c). Will come out in the next release 😅

**Comment by sircharlo** [comment]
Actually, I like grouping better... 
New release will look like this: 
![image](https://user-images.githubusercontent.com/1275666/167943119-3ee7dd72-0621-4d3a-a067-51bae46bae7e.png)

**Comment by joaochris** [comment]
@sircharlo In this case I think you could just leave the main window icon for both. 😀

**Comment by sircharlo** [comment]
I'm kind of thinking that too...

**Comment by joaochris** [comment]
> I'm kind of thinking that too...

I think it was just to differentiate. But as you've already grouped the two, I believe you don't need to 😉

**Comment by sircharlo** [comment]
I'll close this, as next release will take care of this.
