### ISSUE TITLE
Kernel Sandboxing for Linux

### ISSUE THREAD

**Issue by JasonRaveling** [sircharlo/jw-meeting-media-fetcher#6]
This is not necessarily an issue but I thought I'd post it in case it is of use to anyone else. For some distros of Linux you need to be root to use sandboxing. So you'll get the following message when you try to run the fetcher.

> [34860:0131/084140.935538:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_JW-MeeGVVC86/chrome-sandbox is owned by root and has mode 4755.

To solve this you can run `sudo sysctl kernel.unprivileged_userns_clone=1`

I have been downloading media manually and decided to do a quick search on GitHub to see if anyone had made a tool like this. Good timing! It looks like you have just put it on GitHub. Thanks for sharing it! I'm very glad there is an AppImage.

**Comment by sircharlo** [comment]
Thanks so much for bringing this to my attention! I hadn't experienced that with my distro of choice (Zorin), but I've updated the README with info about that error and how to get around it if needed.
